apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dokuwiki-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dokuwiki
  name: dokuwiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dokuwiki
  template:
    metadata:
      labels:
        app: dokuwiki
    spec:
      containers:
      - name: dokuwiki-container
        image: lscr.io/linuxserver/dokuwiki
        env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: TZ
          value: "America/Argentina/Buenos_Aires"
        ports:
        - containerPort: 80
          name: "http-wiki"
        volumeMounts:
        - mountPath: "/config"
          name: dokuwiki-storage
      volumes:
      - name: dokuwiki-storage
        persistentVolumeClaim:
          claimName: dokuwiki-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: dokuwiki-service  # Choose a descriptive name
spec:
  selector:
    app: dokuwiki
  ports:
  - protocol: TCP
    port: 9169  # External port exposed to the cluster
    targetPort: 80  # Port on the pods that the service forwards traffic to (DokuWiki container port)
  type: NodePort  # Expose the service on all nodes with a random high-numbered port
