apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dokuwiki
  name: dokuwiki-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dokuwiki
  labels:
    app: dokuwiki
  name: dokuwiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dokuwiki
  template:
    metadata:
      labels:
        app: dokuwiki
    spec:
      containers:
      - name: dokuwiki-container
        image: lscr.io/linuxserver/dokuwiki
        env:
        - name: PUID
          value: "1001"
        - name: PGID
          value: "1001"
        - name: TZ
          value: "America/Argentina/Buenos_Aires"
        ports:
        - containerPort: 80
          name: "http-wiki"
        volumeMounts:
        - mountPath: "/config"
          name: dokuwiki-storage
      volumes:
      - name: dokuwiki-storage
        persistentVolumeClaim:
          claimName: dokuwiki-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: dokuwiki-service
  namespace: dokuwiki
spec:
  selector:
    app: dokuwiki
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dokuwiki-ingress
  namespace: dokuwiki
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /wiki
            backend:
              service:
                name: dokuwiki-service
                port:
                  number: 80
